#!/bin/sh
set -e

# This will only remove masks created by d-s-h on package removal.
deb-systemd-helper unmask tsample.service > /dev/null || true

# was-enabled defaults to true, so new installations run enable.
if deb-systemd-helper --quiet was-enabled tsample.service
then
	# Enables the unit on first installation, creates new
	# symlinks on upgrades if the unit file has changed.
	deb-systemd-helper enable tsample.service > /dev/null || true
	deb-systemd-invoke start tsample
else
	# Update the statefile to add new symlinks (if any), which need to be
	# cleaned up on purge. Also remove old symlinks.
	deb-systemd-helper update-state tsample.service > /dev/null || true
fi